import { NextRequest, NextResponse } from 'next/server';
import { buildDigestFromDb, writeCoachReport } from '@/lib/ai/coach-report';
import { noteAiFailure } from '@/lib/ai/guard';
import { tierOf } from '@matricmate/core';
import { planIsActive } from '@/lib/entitlement';
import { notify, reportReady } from '@/lib/notify';
import { JobError, chunks, cronAuthorised, eachLimited, pageAll, logged } from '@/lib/notify/jobs';
import { createAdminClient } from '@/lib/supabase/admin';

/**
 * Rewrites the coach card for students who have studied since their last one.
 *
 * The card used to be generated by whoever opened the dashboard first, which
 * had two costs: that student waited on a model call to see their own home
 * screen, and the report was keyed by week, so it said the same thing from
 * Monday to Sunday no matter how much they had done in between.
 *
 * Doing it here decouples the two. The card only ever reads, so it paints
 * instantly, and a student who studies every day gets a report that keeps up
 * with them.
 *
 * Scoped to real activity on purpose. A report costs a model call, so this
 * skips anyone who has not answered a question since their last report, and
 * anyone whose report is less than a day old. Idle accounts cost nothing, and
 * neither do staff or accounts without a plan, who cannot see the card.
 *
 * Oldest report first. The list used to be ordered by latest activity, so the
 * same most-active slice filled every night's run and the rest never got a
 * turn. A second pg_cron entry an hour later (migration 0040) finishes what
 * the first could not; the one-a-day rule makes running twice harmless.
 */

export const maxDuration = 300;

/** A day's worth, so a student gets at most one rewrite per day. */
const MIN_AGE_MS = 20 * 60 * 60 * 1000;
/** A ceiling per run, so one night can never turn into an unbounded bill. */
const MAX_PER_RUN = 200;
/** Reports written at once. One after another, a night reached about 25. */
const CONCURRENCY = 4;
/**
 * When to stop starting new reports. A model call is allowed a minute and one
 * retry (lib/ai/coach-report), so one started just before this still finishes
 * inside the five minute limit.
 */
const BUDGET_MS = 170_000;

export const GET = logged('coach', handle);

async function handle(req: NextRequest) {
  /*
   * pg_cron signs its calls with CRON_SECRET. Without this the route is a
   * button on the open internet that spends the client's model budget.
   */
  if (!cronAuthorised(req)) {
    return NextResponse.json({ error: 'unauthorised' }, { status: 401 });
  }
  try {
    /*
     * `?user=<id>` rewrites that one student's report now, whether or not the
     * nightly rules would, and nobody else's. For support ("my coach card is
     * empty") and for testing a change without writing, and pushing, reports
     * for every student who studied today.
     */
    const only = req.nextUrl.searchParams.get('user');
    return await run(only && /^[0-9a-f-]{36}$/i.test(only) ? only : null);
  } catch (e) {
    console.error('[cron/coach] run failed', e instanceof Error ? e.message : e);
    return NextResponse.json(
      { error: 'incomplete', stage: e instanceof JobError ? e.stage : 'unknown', detail: e instanceof Error ? e.message : String(e) },
      { status: 503 },
    );
  }
}

async function run(only: string | null = null): Promise<NextResponse> {
  const startedAt = Date.now();
  const admin = createAdminClient();
  const now = Date.now();
  const period = new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Karachi' }).format(new Date());

  if (only) {
    const digest = await buildDigestFromDb(admin, only);
    const written = digest ? await writeCoachReport(admin, only, digest, period) : false;
    if (written) await notify(only, reportReady());
    return NextResponse.json({ user: only, digest: Boolean(digest), written });
  }

  // Students who did something in the last day. Nobody else needs a rewrite.
  const since = new Date(now - 26 * 60 * 60 * 1000).toISOString();
  const active = await pageAll<{ user_id: string }>('attempts', (from, to, signal) =>
    admin.from('attempts').select('user_id').gte('at', since).order('at', { ascending: false }).order('id').range(from, to).abortSignal(signal),
  );
  const recent = [...new Set(active.map((r) => r.user_id))];
  if (!recent.length) return NextResponse.json({ considered: 0, written: 0, skipped: 0 });

  // Students with a plan, and when each was last written for.
  const students = new Set<string>();
  const paying = new Set<string>();
  const lastWritten = new Map<string, number>();
  const monthAgo = new Date(now - 30 * 864e5).toISOString();
  for (const slice of chunks(recent)) {
    const [profiles, plans, reports] = await Promise.all([
      pageAll<{ id: string }>('profiles', (from, to, signal) =>
        admin.from('profiles').select('id').in('id', slice).eq('role', 'student').order('id').range(from, to).abortSignal(signal),
      ),
      pageAll<{ user_id: string; active: boolean | null; valid_till: string | null; plan: string | null }>('entitlements', (from, to, signal) =>
        admin.from('entitlements').select('user_id,active,valid_till,plan').in('user_id', slice).order('user_id').range(from, to).abortSignal(signal),
      ),
      pageAll<{ user_id: string; period: string; created_at: string }>('coach_reports', (from, to, signal) =>
        admin
          .from('coach_reports')
          .select('user_id,period,created_at')
          .in('user_id', slice)
          .gte('created_at', monthAgo)
          .order('user_id')
          .order('period')
          .range(from, to)
          .abortSignal(signal),
      ),
    ]);
    for (const p of profiles) students.add(p.id);
    // Premium only: the report is written by a model, and Basic has no AI; a
    // three-day trial is not worth a nightly report either.
    for (const e of plans) if (planIsActive(e) && tierOf(e.plan) === 'premium') paying.add(e.user_id);
    for (const r of reports) lastWritten.set(r.user_id, Math.max(lastWritten.get(r.user_id) ?? 0, Date.parse(r.created_at)));
  }

  // Never written for comes first, then the longest waiting.
  const eligible = recent
    .filter((id) => students.has(id) && paying.has(id))
    .filter((id) => now - (lastWritten.get(id) ?? 0) >= MIN_AGE_MS)
    .sort((a, b) => (lastWritten.get(a) ?? 0) - (lastWritten.get(b) ?? 0));
  const batch = eligible.slice(0, MAX_PER_RUN);
  const dropped = eligible.length - batch.length;
  if (dropped) console.warn(`[cron/coach] ${dropped} students over the per-run ceiling, left for the next run`);

  const stopAt = startedAt + BUDGET_MS;
  let written = 0;
  let skipped = 0;
  let failed = 0;
  const reached = await eachLimited(
    batch,
    CONCURRENCY,
    async (userId) => {
      // One student's bad report must not end the run for everyone after them.
      try {
        const digest = await buildDigestFromDb(admin, userId);
        if (!digest) {
          skipped++;
          return;
        }
        if (await writeCoachReport(admin, userId, digest, period)) {
          written++;
          // Tell them it exists. A report nobody knows was rewritten is a
          // report nobody reads, and the inbox's own empty state has always
          // promised exactly this.
          await notify(userId, reportReady());
        } else skipped++;
      } catch (e) {
        failed++;
        console.error('[cron/coach] report failed', e instanceof Error ? e.message : e);
        await noteAiFailure(e);
      }
    },
    () => Date.now() > stopAt,
  );

  const unfinished = batch.length - reached;
  const summary = { considered: eligible.length, written, skipped, failed, unfinished, dropped };
  // Not everyone reached: a non-200 so it shows, and the second run finishes.
  if (failed || unfinished || dropped) return NextResponse.json({ error: 'incomplete', ...summary }, { status: 503 });
  return NextResponse.json(summary);
}
