import { NextRequest, NextResponse } from 'next/server';
import { translate } from '@matricmate/core';
import type { Language } from '@matricmate/core';
import { buildDigestFromDb, writeCoachReport } from '@/lib/ai/coach-report';
import { createAdminClient } from '@/lib/supabase/admin';

/**
 * Rewrites the coach card for students who have studied since their last one.
 *
 * The card used to be generated by whoever opened the dashboard first, which
 * had two costs: that student waited on a model call to see their own home
 * screen, and the report was keyed by week, so it said the same thing from
 * Monday to Sunday no matter how much they had done in between.
 *
 * Doing it here decouples the two. The card only ever reads, so it paints
 * instantly, and a student who studies every day gets a report that keeps up
 * with them.
 *
 * Scoped to real activity on purpose. A report costs a model call, so this
 * skips anyone who has not answered a question since their last report, and
 * anyone whose report is less than a day old. Idle accounts cost nothing.
 */

export const maxDuration = 300;

/** A day's worth, so a student gets at most one rewrite per day. */
const MIN_AGE_MS = 20 * 60 * 60 * 1000;
/** A ceiling per run, so one night can never turn into an unbounded bill. */
const MAX_PER_RUN = 200;

export async function GET(req: NextRequest) {
  /*
   * Vercel signs its cron calls with CRON_SECRET. Without this the route is a
   * button on the open internet that spends the client's model budget.
   */
  const secret = process.env.CRON_SECRET;
  if (!secret || req.headers.get('authorization') !== `Bearer ${secret}`) {
    return NextResponse.json({ error: 'unauthorised' }, { status: 401 });
  }

  const admin = createAdminClient();
  const now = Date.now();
  const period = new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Karachi' }).format(new Date());

  // Students who did something in the last day. Nobody else needs a rewrite.
  const since = new Date(now - 26 * 60 * 60 * 1000).toISOString();
  const { data: active, error } = await admin
    .from('attempts')
    .select('user_id,at')
    .gte('at', since)
    .order('at', { ascending: false })
    .limit(5000);
  if (error) return NextResponse.json({ error: error.message }, { status: 500 });

  const userIds = [...new Set((active ?? []).map((r) => r.user_id as string))].slice(0, MAX_PER_RUN);

  let written = 0;
  let skipped = 0;
  for (const userId of userIds) {
    const { data: last } = await admin
      .from('coach_reports')
      .select('period,created_at')
      .eq('user_id', userId)
      .order('period', { ascending: false })
      .limit(1)
      .maybeSingle();

    if (last?.created_at && now - Date.parse(last.created_at as string) < MIN_AGE_MS) {
      skipped++;
      continue;
    }

    const digest = await buildDigestFromDb(admin, userId);
    if (!digest) {
      skipped++;
      continue;
    }
    // One student's bad report must not end the run for everyone after them.
    try {
      if (await writeCoachReport(admin, userId, digest, period)) {
        written++;
        // Tell them it exists. A report nobody knows was rewritten is a report
        // nobody reads, and the inbox's own empty state has always promised
        // exactly this.
        const lang: Language = digest.language === 'ur' ? 'ur' : 'en';
        await admin.from('notifications').insert({
          user_id: userId,
          kind: 'report',
          title: translate(lang, 'notifications.reportTitle'),
          body: translate(lang, 'notifications.reportBody'),
          target: 'report',
        });
      } else skipped++;
    } catch {
      skipped++;
    }
  }

  return NextResponse.json({ considered: userIds.length, written, skipped });
}
