-- The coach card, refreshed in the background instead of on first sight.
--
-- Two problems with how it worked. It was keyed by week, so a student read the
-- same three sentences from Monday to Sunday however much they studied in
-- between. And it was generated by whoever opened the dashboard first: the
-- card triggered the model call, so one student paid a slow render for
-- everyone's benefit, and a student with no history got nothing at all
-- because the card returned null rather than say anything.
--
-- The column is renamed because it is no longer a week. A report now covers
-- the last seven days but is rewritten whenever the student has studied since
-- the last one, so `period` is the day it was written for.

alter table public.coach_reports rename column week to period;

-- Which student this report is about, so the cron can find the stale ones
-- without reading every row's body.
create index if not exists coach_reports_user_period_idx
  on public.coach_reports (user_id, period desc);

-- Live, like the rest of the dashboard: when the cron writes a fresh report
-- the student's open tabs and phone pick it up rather than waiting for a
-- reload. Signal only, no body: the topic is public and a coach report is
-- personal.
create or replace function public.broadcast_coach_report()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform realtime.send(
    jsonb_build_object('period', new.period),
    'change',
    'coach:' || new.user_id::text,
    false
  );
  return new;
end;
$$;

drop trigger if exists coach_reports_broadcast on public.coach_reports;

create trigger coach_reports_broadcast
  after insert or update on public.coach_reports
  for each row
  execute function public.broadcast_coach_report();
