import type { Metadata } from 'next';
import { AI_QUOTA } from '@matricmate/core';
import { Nav } from '@/components/landing/Nav';
import { SiteFooter } from '@/components/landing/SiteFooter';
import { BUSINESS, SUPPORT_EMAIL } from '@matricmate/core';
import { canonicalUrl } from '@/lib/site';

export const metadata: Metadata = {
  title: 'Terms and conditions',
  description: 'How MatricMate works, what you are buying, and the rules both sides agree to.',
  alternates: { canonical: canonicalUrl('/terms') },
};

const SECTIONS: { heading: string; paragraphs: string[] }[] = [
  {
    heading: 'What MatricMate is',
    paragraphs: [
      'MatricMate is exam-preparation software for FBISE and Punjab Board Class 9 and Class 10. It gives you notes, audio lessons, practice questions, past papers and an AI tutor. It is a study aid. It does not set, mark or influence any board examination, and it is not affiliated with the Federal Board of Intermediate and Secondary Education, any Board of Intermediate and Secondary Education in Punjab, or the Punjab textbook authority.',
      'Study content follows each board’s own syllabus: the FBISE syllabus and model papers, and for Punjab the official Punjab textbooks and the learning outcomes printed in them. Payments are handled by a State Bank licensed Pakistani payment gateway, which processes cards, wallets and bank transfers on our behalf.',
    ],
  },
  {
    heading: 'Your account',
    paragraphs: [
      'One account, one student. You are responsible for keeping your password to yourself; if you think someone else has it, set a new one with “Forgot password?” on the log in page.',
      'Students under 18 should have a parent or guardian read this page. The monthly report card is a PDF your child downloads and can hand to you, so a parent does not need an account of their own.',
    ],
  },
  {
    heading: 'Paying, and what happens when a plan ends',
    paragraphs: [
      'Plans are sold on this website only. There are two: Basic, which opens every chapter, note, audio lesson and practice question, and Premium, which adds the AI tutor and the other AI features. A new account may also try one subject free for three days, once.',
      'A plan is a single payment for a fixed stretch of time. Nothing renews automatically, no card is kept for a later charge, and the end date is shown on your account from the day you pay.',
      'There is no cancel button because there is no recurring charge to stop. If you do nothing, the plan ends on its last paid day. Access continues to that date, and your progress stays on the account whether or not you pay again.',
      'When you pay through the payment gateway, card, wallet and account details are typed on the gateway’s own page. They go to the gateway, never to us, and we store only the reference number shown on your receipt. When our team switches a plan on for you by hand, we record the payment against your account and keep no card or wallet details.',
    ],
  },
  {
    heading: 'What we store, and why',
    paragraphs: [
      'Your name and contact, your class, board, medium and subject list, and your study activity: which sections you have read, which questions you answered, how sure you were, and your test results. That last part is what makes weak topics and the report card work. Without it the app cannot tell you anything useful.',
      'We do not sell your data, and we do not use it to advertise to you. Questions you ask the AI tutor are sent to the model that answers them and kept so you can see your own history.',
    ],
  },
  {
    heading: 'The AI tutor',
    paragraphs: [
      `The tutor is generated by a language model. It is good at explaining and stepping through work, and it can still be wrong, so check anything surprising against your textbook. A daily limit of ${AI_QUOTA.premium} questions applies so the feature stays affordable for everyone.`,
    ],
  },
  {
    heading: 'Deleting your account',
    paragraphs: [
      `Use the delete account page, or write to ${SUPPORT_EMAIL}, and we will delete the account and everything attached to it within seven days. Receipts are kept as long as tax rules require.`,
    ],
  },
  {
    heading: 'Getting in touch',
    paragraphs: [
      `${BUSINESS.name}, ${BUSINESS.address}, ${BUSINESS.city}, ${BUSINESS.country}.`,
      `${BUSINESS.phone} · ${SUPPORT_EMAIL} · ${BUSINESS.hours}.`,
    ],
  },
];

export default async function TermsPage({ searchParams }: { searchParams: Promise<{ from?: string }> }) {
  // The Android app opens this with ?from=app: no navigation on to pricing.
  const bare = (await searchParams).from === 'app';
  return (
    <>
      <Nav bare={bare} />

      <main className="mx-auto max-w-[720px] px-5 py-14">
        <h1 className="font-display text-mk-h1 text-ink">Terms and conditions</h1>
        <p className="mt-3 text-mk-lead text-ink2">
          Written to be read. If anything here is unclear, ask us and we will explain it, and fix the wording.
        </p>

        <div className="mt-10 flex flex-col gap-9">
          {SECTIONS.map((s) => (
            <section key={s.heading}>
              <h2 className="font-display text-[22px] text-ink">{s.heading}</h2>
              {s.paragraphs.map((p, i) => (
                <p key={i} className="mt-2 text-mk-body leading-[1.75] text-ink2">
                  {p}
                </p>
              ))}
            </section>
          ))}
        </div>
      </main>

      <SiteFooter bare={bare} />
    </>
  );
}
