import type { Metadata } from 'next';
import { Nav } from '@/components/landing/Nav';
import { SiteFooter } from '@/components/landing/SiteFooter';

export const metadata: Metadata = {
  title: 'Terms and privacy',
  description: 'How MatricMate works, what we store, and what happens to your data.',
};

const SECTIONS: { heading: string; paragraphs: string[] }[] = [
  {
    heading: 'What MatricMate is',
    paragraphs: [
      'MatricMate is exam-preparation software for FBISE Class 9. It gives you notes, audio lessons, practice questions, past papers and an AI tutor. It is a study aid. It does not set, mark or influence any board examination, and it is not affiliated with the Federal Board of Intermediate and Secondary Education.',
      'This is a prototype build. The content shown is a sample set for review, and the payment flow does not take real money.',
    ],
  },
  {
    heading: 'Your account',
    paragraphs: [
      'One account, one student. You are responsible for keeping your password to yourself; if you think someone else has it, change it from Profile → Settings.',
      'Students under 18 should have a parent or guardian read this page. Parents can see a shared report card without needing an account of their own.',
    ],
  },
  {
    heading: 'Paying, renewing and cancelling',
    paragraphs: [
      'Premium is sold on this website only. Nothing renews automatically: two days before your plan ends we send a reminder, and you choose whether to pay again.',
      'You can cancel any time from Profile → Subscription. Access continues to the date you have already paid for, and chapters you downloaded stay on your device.',
      'Payments are processed by Safepay. Card and mobile-wallet details go to them, not to us, and we store only the reference number shown on your receipt.',
    ],
  },
  {
    heading: 'What we store, and why',
    paragraphs: [
      'Your name and contact, your class, board, medium and subject list, and your study activity: which sections you have read, which questions you answered, how sure you were, and your test results. That last part is what makes weak topics and the report card work. Without it the app cannot tell you anything useful.',
      'We do not sell your data, and we do not use it to advertise to you. Questions you ask the AI tutor are sent to the model that answers them and kept so you can see your own history.',
    ],
  },
  {
    heading: 'The AI tutor',
    paragraphs: [
      'The tutor is generated by a language model. It is good at explaining and stepping through work, and it can still be wrong, so check anything surprising against your textbook. Daily limits apply so the feature stays affordable: 5 questions a day on the free plan, 20 on Premium.',
    ],
  },
  {
    heading: 'Deleting your account',
    paragraphs: [
      'Message us on WhatsApp or write to help@matricmate.pk and we will delete the account and everything attached to it within seven days. Receipts are kept as long as tax rules require.',
    ],
  },
  {
    heading: 'Getting in touch',
    paragraphs: ['help@matricmate.pk · WhatsApp support, 10am–10pm.'],
  },
];

export default function TermsPage() {
  return (
    <>
      <Nav />

      <main className="mx-auto max-w-[720px] px-5 py-14">
        <h1 className="font-display text-[34px] leading-tight text-ink">Terms and privacy</h1>
        <p className="mt-2 text-[14px] text-ink2">
          Written to be read. If anything here is unclear, ask us and we will explain it, and fix the wording.
        </p>

        <div className="mt-10 flex flex-col gap-9">
          {SECTIONS.map((s) => (
            <section key={s.heading}>
              <h2 className="font-display text-[20px] text-ink">{s.heading}</h2>
              {s.paragraphs.map((p, i) => (
                <p key={i} className="mt-2 text-[14.5px] leading-[1.75] text-ink2">
                  {p}
                </p>
              ))}
            </section>
          ))}
        </div>
      </main>

      <SiteFooter />
    </>
  );
}
